micronaut:
  application:
    name: micronautguide
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:}
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true